# Generated by Django 4.2.13 on 2024-06-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_urlimguser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlimguser',
            old_name='img_user',
            new_name='imgUser',
        ),
        migrations.AlterField(
            model_name='urlimguser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='urlimguser',
            table='urlImgUser',
        ),
    ]
