# Generated by Django 4.2.13 on 2024-06-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_img_user_urlimguser_imguser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlimguser',
            name='imgUser',
        ),
    ]
