# Generated by Django 4.2.13 on 2024-06-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_urlimguser_imguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlimguser',
            name='imgUser',
            field=models.TextField(null=True),
        ),
    ]
